databases:
  - name: capital-quiz-db
    databaseName: capital_quiz
    user: capital_quiz
    region: oregon

services:
  - type: web
    name: capital-quiz-backend
    env: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn capital_quiz.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: capital-quiz-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: WEB_CONCURRENCY
        value: 4